name: Build VK Desktop

on:
  release:
    types: [published]

jobs:
  build_on_mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: 12.11.1
    - name: Install dependencies
      run: |
        npm i -g npm
        npm i
    - name: Package electron app and create installer
      run: npm run build
    - name: Upload VK-Desktop.dmg
      uses: JasonEtco/upload-to-release@master
      with:
        args: ./out/VK-Desktop.dmg application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_on_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: 12.11.1
    - name: Install node-gyp
      run: npm install -g node-gyp
    - name: Set node config to use python2.7
      run: npm config set python python2.7
    - name: Set node config to set msvs_version to 2015
      run: npm config set msvs_version 2015
    - name: Work around for Windows Server 2019
      run: set path=%path%;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin
    - name: Install dependencies
      run: |
        npm install
        npm run rebuild
    - name: Build Electron app
      run: npm run build
    - name: Create installer
      run: npm run win-setup

    - name: Upload x64 installer
      uses: JasonEtco/upload-to-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: ./out/VK-Desktop-Setup-x64.exe application/octet-stream

    - name: Upload x32 installer
      uses: JasonEtco/upload-to-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: ./out/VK-Desktop-Setup-x32.exe application/octet-stream

    - name: Upload x64 zip file
      uses: JasonEtco/upload-to-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: ./out/VK-Desktop-Setup-x64.zip application/zip

    - name: Upload ia32 zip file
      uses: JasonEtco/upload-to-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: ./out/VK-Desktop-Setup-ia32.zip application/zip
